spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 5000
      keepalive-time: 30000
      max-lifetime: 600000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
