FROM eclipse-temurin:21-jre-alpine

RUN addgroup -S maple && adduser -S maple -G maple

ARG JAR_PATH=module-app/build/libs/module-app-0.0.1-SNAPSHOT.jar
COPY ${JAR_PATH} /app.jar

ENV JAVA_OPTS="-Xms512m -Xmx1g"
ENV SPRING_PROFILES_ACTIVE=prod

USER maple
WORKDIR /app

EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]
