service:
  log_level: info

input:
  - name: tail
    path: /var/log/app/*.log
    parser: logstash_json
    tag: app.*
    mem_buf_limit: 5MB
    skip_long_lines: on
    refresh_interval: 5
    read_from_head: true

output:
  - name: es
    match: app.*
    host: elasticsearch
    port: 9200
    logstash_format: on
    logstash_prefix: logs
    replace_dots: on
    retry_limit: false
    buffer_size: 4KB
