service:
  log_level: info

input:
  - name: tail
    path: /var/log/containers/*.log
    parser: docker_json
    tag: kube.*
    mem_buf_limit: 5MB
    skip_long_lines: on
    refresh_interval: 5

filter:
  - name: parser
    match: kube.*
    key_name: log
    parser: logstash_json
    reserve_data: on

output:
  - name: es
    match: kube.*
    host: elasticsearch
    port: 9200
    logstash_format: on
    logstash_prefix: logs
    replace_dots: on
    retry_limit: false
    buffer_size: 4KB
