[SERVICE]
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name          tail
    Path          /var/log/app/module-external-api/logs/*.log,/var/log/app/module-calculator/logs/*.log,/var/log/app/module-synchronizer/logs/*.log
    Path_Key      filename
    Parser        logstash_json
    Tag           app.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines on
    Refresh_Interval 5
    Read_From_Head true

[OUTPUT]
    Name            es
    Match           app.*
    Host            elasticsearch
    Port            9200
    Logstash_Format On
    Logstash_Prefix logs-fluentbit
    Replace_Dots    On
    Retry_Limit     False
    Suppress_Type_Name On
